'------------------------------------------------------------------------------
' <auto-generated>
'     Этот код создан программой.
'     Исполняемая версия:4.0.30319.42000
'
'     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
'     повторной генерации кода.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Этот класс создан автоматически классом StronglyTypedResourceBuilder
    'с помощью такого средства, как ResGen или Visual Studio.
    'Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    'с параметром /str или перестройте свой проект VS.
    '''<summary>
    '''  Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("КурсоваяРаботаПоVB.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Перезаписывает свойство CurrentUICulture текущего потока для всех
        '''  обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CoinUp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CoinUp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.IO.UnmanagedMemoryStream, аналогичного System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property fallout_3_death() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("fallout_3_death", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.IO.UnmanagedMemoryStream, аналогичного System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property fallout_4_end_song() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("fallout_4_end_song", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.IO.UnmanagedMemoryStream, аналогичного System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property fallout_4_xp_gain() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("fallout_4_xp_gain", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.IO.UnmanagedMemoryStream, аналогичного System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property fallout_new_vegas() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("fallout_new_vegas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.IO.UnmanagedMemoryStream, аналогичного System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property fallout_shelter_caps() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("fallout_shelter_caps", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Main() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Main", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.IO.UnmanagedMemoryStream, аналогичного System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Main_Theme___Fallout__New_Vegas() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Main_Theme___Fallout__New_Vegas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.IO.UnmanagedMemoryStream, аналогичного System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Menu_Click() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Menu_Click", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.IO.UnmanagedMemoryStream, аналогичного System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Menu_Select() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Menu_Select", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property table() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("table", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Б_10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Б_10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Б_6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Б_6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Б_7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Б_7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Б_8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Б_8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Б_9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Б_9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Б_joker() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Б_joker", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Б_В() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Б_В", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Б_Д() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Б_Д", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Б_К() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Б_К", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Б_Т() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Б_Т", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property В_10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("В_10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property В_6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("В_6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property В_7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("В_7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property В_8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("В_8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property В_9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("В_9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property В_joker() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("В_joker", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property В_В() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("В_В", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property В_Д() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("В_Д", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property В_К() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("В_К", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property В_Т() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("В_Т", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property К_10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("К_10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property К_6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("К_6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property К_7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("К_7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property К_8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("К_8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property К_9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("К_9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property К_joker() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("К_joker", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property К_В() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("К_В", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property К_Д() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("К_Д", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property К_К() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("К_К", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property К_Т() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("К_Т", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Ч_10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ч_10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Ч_6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ч_6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Ч_7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ч_7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Ч_8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ч_8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Ч_9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ч_9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Ч_joker() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ч_joker", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Ч_В() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ч_В", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Ч_Д() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ч_Д", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Ч_К() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ч_К", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Ч_Т() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ч_Т", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Шапка() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Шапка", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
